name: Build and Release EXE

on:
  push:
    tags:
      - '*'  # Запускается при пуше любого тега
  workflow_dispatch:  # Возможность запуска вручную

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.10.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build exe with PyInstaller
        run: pyinstaller --onefile --name AutoGpuAffinity main.py

      - name: Prepare files for 7z Archive
        shell: cmd
        run: |
          mkdir AutoGpuAffinity
          copy /Y dist\AutoGpuAffinity.exe AutoGpuAffinity\AutoGpuAffinity.exe
          copy /Y config.ini AutoGpuAffinity\config.ini
          xcopy /E /I /Y bin AutoGpuAffinity\bin

      - name: Create 7z Archive
        shell: cmd
        run: |
          "C:\Program Files\7-Zip\7z.exe" a AutoGpuAffinity_Windows.7z AutoGpuAffinity\*

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: autogpuaffinity-archive
          path: AutoGpuAffinity_Windows.7z

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.9
        with:
          name: autogpuaffinity-archive

      - name: Create GitHub Release
        id: create_release
        continue-on-error: true
        uses: ncipollo/release-action@v1.16.0
        with:
          tag: ${{ github.ref }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: AutoGpuAffinity_Windows.7z
